"""widen_complaint_number_to_varchar50

Revision ID: 9d130231ad17
Revises: a38a9e1ffd2a
Create Date: 2026-09-17 12:05:32.322483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d130231ad17'
down_revision: Union[str, Sequence[str], None] = 'a38a9e1ffd2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'complaint_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               comment='Human-readable business ID, e.g. CC-20260917063311-529',
               existing_comment='Human-readable business ID, e.g. CC-2026-00154',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'complaint_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               comment='Human-readable business ID, e.g. CC-2026-00154',
               existing_comment='Human-readable business ID, e.g. CC-20260917063311-529',
               existing_nullable=False)
    # ### end Alembic commands ###
