"""Add duplicate fields and embedding

Revision ID: a36698bf7c9a
Revises: 9e44e0450743
Create Date: 2026-09-17 10:57:35.471870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'a36698bf7c9a'
down_revision: Union[str, Sequence[str], None] = '9e44e0450743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.execute("CREATE TYPE duplicatestatus AS ENUM ('UNIQUE', 'POSSIBLE_DUPLICATE', 'DUPLICATE')")
    op.add_column('complaints', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True, comment='all-MiniLM-L6-v2 vector for duplicate detection'))
    op.add_column('complaints', sa.Column('duplicate_status', sa.Enum('UNIQUE', 'POSSIBLE_DUPLICATE', 'DUPLICATE', name='duplicatestatus', create_constraint=True), server_default='UNIQUE', nullable=False))
    op.add_column('complaints', sa.Column('matched_complaint_id', sa.UUID(), nullable=True, comment='ID of the best matching historical complaint, if any'))
    op.create_foreign_key(None, 'complaints', 'complaints', ['matched_complaint_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('complaints_matched_complaint_id_fkey', 'complaints', type_='foreignkey')
    op.drop_column('complaints', 'matched_complaint_id')
    op.drop_column('complaints', 'duplicate_status')
    op.drop_column('complaints', 'embedding')
    op.execute("DROP TYPE duplicatestatus")
    # ### end Alembic commands ###
