"""Add severity and capa_recommendation to RiskAssessment

Revision ID: a38a9e1ffd2a
Revises: a649d3b1b769
Create Date: 2026-09-17 11:29:12.691726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a38a9e1ffd2a'
down_revision: Union[str, Sequence[str], None] = 'a649d3b1b769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_assessments', sa.Column('severity', sa.String(length=20), nullable=True, comment='Minor, Major, Critical'))
    op.add_column('risk_assessments', sa.Column('capa_recommendation', sa.Text(), nullable=True, comment='Original combined CAPA string'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_assessments', 'capa_recommendation')
    op.drop_column('risk_assessments', 'severity')
    # ### end Alembic commands ###
