"""update_risk_assessment_schema

Revision ID: a649d3b1b769
Revises: a36698bf7c9a
Create Date: 2026-09-17 11:17:26.546615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a649d3b1b769'
down_revision: Union[str, Sequence[str], None] = 'a36698bf7c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_assessments', sa.Column('severity_score', sa.Integer(), nullable=True, comment='Severity score 1-10'))
    op.add_column('risk_assessments', sa.Column('risk_level', sa.String(length=20), nullable=True, comment='LOW, MEDIUM, HIGH, CRITICAL'))
    op.add_column('risk_assessments', sa.Column('corrective_action', sa.Text(), nullable=True))
    op.add_column('risk_assessments', sa.Column('preventive_action', sa.Text(), nullable=True))
    op.drop_column('risk_assessments', 'severity')
    op.drop_column('risk_assessments', 'capa_recommendation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_assessments', sa.Column('capa_recommendation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('risk_assessments', sa.Column('severity', postgresql.ENUM('Minor', 'Major', 'Critical', name='riskseverity'), autoincrement=False, nullable=False))
    op.drop_column('risk_assessments', 'preventive_action')
    op.drop_column('risk_assessments', 'corrective_action')
    op.drop_column('risk_assessments', 'risk_level')
    op.drop_column('risk_assessments', 'severity_score')
    # ### end Alembic commands ###
